### ISSUE TITLE
6.2 Credential Revocation - Cover for LDAP being unavailable. 

### ISSUE THREAD

**Issue by britpayson** [Open-Credentialing-Initiative/Credential-Issuer-Conformance-Criteria#10]
Based on the current version of the Credential Issuer Conformance Criteria there is a gap in regards to what should be done if LDAP is unavailable. The only option given is to reference a cached copy no older than 24hrs; however there is no direction on what must be done if there is no access / recent (ie 24hrs or less) cached version available. 

**Addressed by** https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/issues/76

**Comment by bluesteens** [comment]
**Triage:**

- [x] Is Issue appropriate for OCI Architecture
- [ ] Create Steering-level Summary of request
- [x] Assign **Size**
- [x] Assign **Priority**
- [x] Assign **Label** (if needed)
- [x] OCI affected Artifacts Identified
- [ ] Assign **Triage - Artifact Version Target** (v x.x.x Milestone)
- [ ] Assign **Triage - Interop Profile Version Target** (v x.x.x Milestone)
- [ ] Create sub-project (if needed)


**Affected Parties (help determine Sunrise/Sunset):**
    
- [ ] Trading Partners
- [x] Issuers 
- [ ] Wallet Solutions
- [ ] PI Verification Solutions  

**Affected OCI Artifact**
    
- [ ] Schema Document
- [ ] Identity Schema
- [ ] ATP Schema
- [x] Issuer Conformance Criteria
- [ ] Wallet Conformance Criteria
- [ ] VRS Solution Conformance Criteria
- [ ] Wallet API Specification
- [ ] Governance Document
- [ ] Conformance Program
- [ ] OCI Website
- [ ] Internal Process  

**Change Category (Guides Steering Review)**

   **- Steering/Industry Review**    
- [ ] Business-Level (May affect business operations)
- [ ] OCI Governance, Policy or website feature

**- Steering/Industry Notification**
- [x] Technical-Level (Do not affect business operations)
- [ ] OCI Internal Process or Infrastructure
