### ISSUE TITLE
remove vc-htttp-api from CI criteria

### ISSUE THREAD

**Issue by bluesteens** [Open-Credentialing-Initiative/Credential-Issuer-Conformance-Criteria#12]
when we removed vc-http-api from the wallet criteria, we forgot to fix this in the CI criteria

6.1 General [Requirements](https://open-credentialing-initiative.github.io/Credential-Issuer-Conformance-Criteria/#general-requirements)

> A Credential Issuer SHALL:
> Use either the DIDComm Messaging v2 or the vc-http-api method for requesting from or issuing Identity and ATP credentials to a trading partner.

**Comment by bluesteens** [comment]
- [x]  Is Issue appropriate for OCI Architecture
- [ ] Create Steering-level Summary of request
- [x]  Assign Size
- [x]  Assign Priority
- [x]  Assign Label (if needed)
- [x]  OCI affected Artifacts Identified
- [ ]  Assign Triage - Artifact Version Target (v x.x.x Milestone)
- [ ]  Assign Triage - Interop Profile Version Target (v x.x.x Milestone)
- [ ]  Create sub-project (if needed)


**Affected Parties (help determine Sunrise/Sunset):**
    
- [ ] Trading Partners
- [ ] Issuers 
- [ ] Wallet Solutions
- [ ] PI Verification Solutions  

**Affected OCI Artifact**
    
- [ ] Schema Document
- [ ] Identity Schema
- [ ] ATP Schema
- [x] Issuer Conformance Criteria
- [ ] Wallet Conformance Criteria
- [ ] VRS Solution Conformance Criteria
- [ ] Wallet API Specification
- [ ] Governance Document
- [ ] Conformance Program
- [ ] OCI Website
- [ ] Internal Process  

**Change Category (Guides Steering Review)**

   **- Steering/Industry Review**    
- [ ] Business-Level (May affect business operations)
- [ ] OCI Governance, Policy or website feature

**- Steering/Industry Notification**
- [x] Technical-Level (Do not affect business operations)
- [ ] OCI Internal Process or Infrastructure

**Comment by bluesteens** [comment]
maybe include in work on issue [#31](https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/issues/31)

**Comment by rceleste125** [comment]
See if we can reference the removal of vc-http-api work.

Pull Request 26:  https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/issues/15 

Typo: Made decision in 2022, adjusting Issuer conformance to reflect the change.

**Comment by bluesteens** [comment]
removal of vc-http-api: 
https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/pull/26
https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/issues/15

**Comment by bluesteens** [comment]
July, 27: to be released in Credential Issuer Criteria v2.1.1, interop profile v3.2.0
